<FirstWindow>:
    name: "first"
    GridLayout:
        cols: 2
        size: root.width, root.height
        padding: 50
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
        BoxLayout:
            orientation: 'vertical'
            padding: 20
            spacing: 10
            Label:
                text: "Button 1"
                size_hint: None, None
            Label:
                text: "Button 2"
                size_hint: None, None
            Label:
                text: "Button 3"
                size_hint: None, None

            RoundedButton:
                text: "Next Screen"
                font_size: 32
                size: (340, 130)
                pos_hint: {'x': 0.30, 'y': 0.27}  # Combined pos_hint into one dictionary
                size_hint: (None, None)
                on_release:
                    app.root.current = "second"
                    root.manager.transition.direction = "up"
        Image:
            source: "start_window.png"
