WindowManager:
    FirstWindow:
    SecondWindow:


<FirstWindow>:
    name: "first"
    GridLayout:
        cols: 2
        size: root.width, root.height
        padding: 50
        canvas.before:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                source:"frame.png"
        BoxLayout:
            orientation: 'vertical'
            padding: 20
            spacing: 10
            Label:
                text: "Button 1"
                size_hint: None, None
            Label:
                text: "Button 2"
                size_hint: None, None
            Label:
                text: "Button 3"
                size_hint: None, None

            RoundedButton:
                text: "Next Screen"
                font_size: 32
                size: (340,130)
                pos_hint: {'x': 0.30}
                pos_hint: {'y': 0.27}
                size_hint: (None,None)
                on_release:
                    app.root.current = "second"
                    root.manager.transition.direction = "up"
        Image:
            source: "start_window.png"


<RoundedButton@Button>
    background_color: (0,0,0,0)
    background_normal:''
    canvas.before:
        Color:
            rgba: (53/255, 121/255, 92/255,1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [74]



<SecondWindow>:
    name: "second"
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            text: "Second Screen"
            font_size: 32

        Button:
            text: "Next Screen"
            font_size: 32
            on_release:
                app.root.current = "first"
                root.manager.transition.direction = "down"