WindowManager:


    LastWindow:


<FirstWindow>:
    name: "first"
    GridLayout:
        cols: 2
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        GridLayout:
            rows: 3
            FloatLayout:
                Label:
                    text: "Welcome to\nEcomate trash can!"
                    color: (53/255, 121/255, 92/255, 1)
                    font_size: 60
                    pos: (-110, 220)
                Label:
                    text: "This bin will automatically\nidentify and sort your\nwaste"
                    color: (6/255, 15/255, 10/255, 1)
                    font_size: 60
                    pos: (-30, 10)
                FloatLayout:
                    Label:
                        text: "Press"
                        color: (250/255, 107/255, 122/255, 1)
                        font_size: 60
                        pos: (-299, -180)
                    FloatLayout:
                        RoundedButton:
                            text: "start"
                            font_size: 60
                            size: (335, 125)
                            pos: (280, 250)
                            size_hint: None, None
                            on_release:
                                app.root.current = "second"
                                root.manager.transition.direction = "up"
                    Label:
                        text: "to begin!"
                        color: (250/255, 107/255, 122/255, 1)
                        font_size: 60
                        pos: (270, -180)
        Image:
            source: "images/start_window.png"

<RoundedButton@Button>:
    background_color: (0, 0, 0, 0)
    background_normal: ''
    canvas.before:
        Color:
            rgba: (53/255, 121/255, 92/255, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [74]

<SecondWindow>:
    name: "second"
    FloatLayout:
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        BoxLayout:
            orientation: 'vertical'
            spacing: -10
            FloatLayout:
                Image:
                    source: "images/rec_frame.png"
                    pos: (-110, 500)
                Image:
                    id: rectangle
                    source: "images/rectangle.png"
                    background_color: (53/255, 121/255, 92/255, 1)
                    pos: (-35, 500)
            FloatLayout:
                Label:
                    text: "Door Opening"
                    font_size: 70
                    color: (53/255, 121/255, 92/255, 1)
                    pos: (-110, 275)
            FloatLayout:
                Image:
                    source: "images/point.png"
                    pos: (-255, 120)
                Label:
                    text: "WARNING\nBEWARE OF MOVING DOOR"
                    font_size: 60
                    color: (250/255, 107/255, 122/255, 1)
                    pos: (200, 120)
            Button:
                text: "Play"
                background_normal: ''
                font_size: 20
                size: (200, 39)
                size_hint: (None, None)
                on_release:
                    app.animate_frame(rectangle)
            Button:
                text: "Next Screen"
                font_size: 20
                background_normal: ''
                size: (200, 39)
                size_hint: (None, None)
                on_release:
                    app.root.current = "third"
                    root.manager.transition.direction = "down"

<ThirdWindow>:
    name: "third"
    FloatLayout:
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        FloatLayout:
            Image:
                source: "images/bottle_frame.png"
                pos_hint: {'center_y': 0.65}
            Image:
                id: bottle
                source: "images/bottle.png"
                pos_hint: {'center_y': 0.74}
            Label:
                text: "Please Insert item"
                font_size: 70
                color: (53/255, 121/255, 92/255, 1)
                pos_hint: {'center_x': 0.48, 'center_y': 0.42}
            GridLayout:
                cols: 2
                FloatLayout:
                    Image:
                        source: "images/small_point.png"
                        pos_hint: {'center_x': 0.72, 'center_y': 0.32}
                FloatLayout:
                    Label:
                        text: "insert One item at a time"
                        font_size: 40
                        color: (250/255, 107/255, 122/255, 1)
                        pos_hint: {'right': 0.52, 'center_y': 0.32}
            RoundedButton:
                text: "close door"
                font_size: 60
                size: (404, 130)
                pos_hint: {'center_x': 0.49, 'y': 0.13}
                size_hint: None, None
                on_release:
                    app.root.current = "drop"
                    root.manager.transition.direction = "up"
        Button:
            text: "Play"
            background_normal: ''
            font_size: 20
            size: (200, 65)
            size_hint: (None, None)
            on_release:
                app.animate_frame2(bottle)

<DropWindow>:
    name: "drop"
    FloatLayout:
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        FloatLayout:
            Image:
                source: "images/bottle_frame.png"
                pos_hint: {'center_y': 0.65}
            Image:
                id: bottle
                source: "images/bottle.png"
                pos_hint: {'center_y': 0.60}
            Label:
                text: "Please Insert item"
                font_size: 70
                color: (53/255, 121/255, 92/255, 1)
                pos_hint: {'center_x': 0.48, 'center_y': 0.42}
            GridLayout:
                cols: 2
                FloatLayout:
                    Image:
                        source: "images/small_point.png"
                        pos_hint: {'center_x': 0.72, 'center_y': 0.32}
                FloatLayout:
                    Label:
                        text: "insert One item at a time"
                        font_size: 40
                        color: (250/255, 107/255, 122/255, 1)
                        pos_hint: {'right': 0.52, 'center_y': 0.32}
            RoundedButton:
                text: "close door"
                font_size: 60
                size: (404, 130)
                pos_hint: {'center_x': 0.49, 'y': 0.13}
                size_hint: None, None
                on_release:
                    app.root.current = "fourth"
                    root.manager.transition.direction = "up"
        Button:
            text: "Play"
            background_normal: ''
            font_size: 20
            size: (200, 65)
            size_hint: (None, None)
            on_release:
                app.animate_frame2(bottle)


<FourthWindow>:
    name: "fourth"
    FloatLayout:
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        GridLayout:
            cols: 2
            FloatLayout:
                Label:
                    text: "Do you have an account?"
                    font_size: 70
                    color: (53/255, 121/255, 92/255, 1)
                    pos_hint: {'center_x': 0.6, 'center_y': 0.65}
                GridLayout:
                    cols: 2
                    FloatLayout:
                        RoundedButton:
                            text: "Yes"
                            font_size: 60
                            size: (335, 125)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                            size_hint: None, None
                            on_release:
                                app.root.current = "fifth"
                                root.manager.transition.direction = "left"
                    FloatLayout:
                        RoundedButton:
                            text: "No"
                            font_size: 60
                            size: (335, 125)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                            size_hint: None, None
                            on_release:
                                app.root.current = "sixth"
                                root.manager.transition.direction = "right"
            FloatLayout:
                Label:
                    text: "Or"
                    font_size: 40
                    color: (250/255, 107/255, 122/255, 1)
                    pos_hint: {'center_x': 0.5, 'center_y': 0.45}

<FifthWindow>:
    name: "fifth"
    FloatLayout:
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "images/frame.png"
                size: (1780, 864)
                pos: (70, 68)
        BoxLayout:
            orientation: 'vertical'
            spacing: 20
            FloatLayout:
                Label:
                    text: "Scan the QR Code"
                    font_size: 70
                    color: (53/255, 121/255, 92/255, 1)
                    pos_hint: {'center_x': 0.5, 'center_y': 0.8}
            Image:
                id: qr_code_image
                source: ''
                size_hint: (None, None)
                size: (1000, 1000)
                pos_hint: {'center_x': 0.20, 'center_y': 0.20}
            Button:
                text: "Back"
                font_size: 20
                size_hint: None, None
                size: (300, 50)
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release:
                    app.root.current = "fourth"
                    root.manager.transition.direction = "right"


<SixthWindow>:
    name: "sixth"
    FloatLayout:
        Label:
            text: "Sixth Window"
            font_size: 70
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

<SeventhWindow>:
    name: "seventh"
    FloatLayout:
        Label:
            text: "Seventh Window"
            font_size: 70
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}


<LastWindow>:
    name: "last"
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: "images/frame.png"
                size: 1780, 864
                pos: 70, 68

        BoxLayout:
            orientation: 'horizontal'
            padding: 50
            spacing: 50
            Image:
                source: "images/thanks_girl.png"  
                size_hint: None, 1
                width: 400
                

                
            Label:
                text: "Thanks for using me :)"
                font_size: 60
                color: 53/255, 121/255, 92/255, 1
                size_hint: None, 1
                width: 400
                halign: 'center'
                valign: 'middle'
                pos: 70,90

