<ClosingScreen>:
    name: "closing"
    GridLayout:
        size: root.width, root.height
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                source: "assets/images/frame.png"
                size: (root.width * 0.9, root.height * 0.9)
                pos: (root.width * 0.05, root.height * 0.05)
    
    GridLayout:
        cols: 2
        FloatLayout:
            Image:
                source: "assets/images/submit_girl.png"
                size_hint: 0.7, 0.7
                pos_hint: {"center_x": 0.6, "center_y": 0.5}          

        FloatLayout:
            Label:
                text: "Thanks for\nusing me !"
                color: (53/255, 121/255, 92/255, 1)
                bold: True
                font_size: root.width * 0.08
                pos_hint: {"center_x": 0.35, "center_y": 0.5}